server:
  #  tomcat:
  #    uri-encoding: UTF-8
  #    max-threads: 1000
  #    min-spare-threads: 30
  port: 8443
  #  connection-timeout: 5000ms
  ssl:

    key-store: classpath:server_ssl.jks

    key-store-password: mVr79x1a

    keyStoreType: JKS



spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.215.42:10257/yidiantong?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://47.99.215.42:10257/yidiantong?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: tongyibingoNMSL1
#    initial-size: 10
#    max-active: 100
#    min-idle: 10
#    max-wait: 60000
#    pool-prepared-statements: true
#    max-pool-prepared-statement-per-connection-size: 20
#    time-between-eviction-runs-millis: 60000
#    min-evictable-idle-time-millis: 300000

    #Oracle需要打开注释
    #validation-query: SELECT 1 FROM DUAL


#    test-while-idle: true
#    test-on-borrow: false
#    test-on-return: false
#    stat-view-servlet:
#      enabled: true
#      url-pattern: /druid/*
#      #login-username: admin
#      #login-password: admin
#    filter:
#      stat:
#        log-slow-sql: true
#        slow-sql-millis: 1000
#        merge-sql: false
#      wall:
#        config:
#          multi-statement-allow: true

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  redis:
    host: 172.17.0.2
    port: 6379
    password:
##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456

# xxl-job配置
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://47.99.215.42:10107/xxl-job-admin
    executor:
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: yibingo-app
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9998
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: logs/xxl-job/jobhandler
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 15
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: