

  #spring:
  #  # 环境 dev|test|prod
  #  profiles:
  #    active: dev
  # jackson时间格式化

#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss

  #  servlet:
  #    multipart:
  #      max-file-size: 100MB
  #      max-request-size: 100MB
  #      enabled: true
#  redis:
#    open: false  # 是否开启redis缓存  true开启   false关闭
#    database: 0
#    host: localhost
#    port: 6379
#    password:    # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


renren:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

#自定义参数，可以迁移走
token:
  #redis默认过期时间（7天）(这是自定义的)(毫秒)
  expirationMilliSeconds: 604800000

#微信相关参数
weChat:
  #小程序appid
  appid: wxfdd42d32410de8d7
  #小程序密钥
  secret: 11b46596c5380dbd62aeb5038ac43724


swagger:
  # 全局统一鉴权配置
  authorization:
    key-name: GitsSessionID


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8